name: MLflow CI Basic

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Set up job (otomatis)
      
      # 2️⃣ Checkout repository
      - name: Run actions/checkout
        uses: actions/checkout@v3

      # 3️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 4️⃣ Check Env
      - name: Check Env
        run: |
          python --version
          pip --version

      # 5️⃣ Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow==2.19.0

      # 6️⃣ Run mlflow project 
      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run .

      # 7️⃣ Get latest MLflow run_id
      - name: Get latest MLflow run_id
        run: |
          echo "MLflow run finished successfully"
